### ISSUE TITLE
Cutting down forests/jungles

### ISSUE THREAD

**Issue by Niuke92** [kblease/ProductionQueue#1]
If you cut down forest/jungles and finish producing whatever nearest city is making in the same turn the queue breaks

**Comment by kblease** [comment]
@Niuke92 Ah! I didn't even think of that. Thanks for bringing it to my attention, I'll look into that as soon as I can.

**Comment by kblease** [comment]
This issue should be fixed now. Thanks again @Niuke92 for reporting it!
