### ISSUE TITLE
Issues after loading a saved game

### ISSUE THREAD

**Issue by mpatel514** [kblease/ProductionQueue#21]
Version 0.1.5

1. Unable to queue after loading a saved game.
2. Unable to place districts or wonders on tiles after loading a saved game.

2 it the bigger deal as it renders the save basically unusable.

Seems to be an issue with This and Divine Yuri's CityPanel.

**Comment by kblease** [comment]
Indeed, Divine Yuri's mod conflicts with this one out of the box. However, Divine Yuri's mod does not need, and barely even uses, the references to the two ProductionPanel files in the .modinfo file. The .xml one is identical to the base game (although, I actually think it's misspelled in the .modinfo file so it's not being used anyway), and the .lua one has a single line difference which is completely unneeded for the mod to function fully.

Now, that is not my mod, so this all is technically just my opinion. But others have reported complete harmony, without the loss of features, between Divine Yuri's mod and Production Queue if you remove the four lines which reference the ProductionPanel files from Divine Yuri's .modinfo file. In fact, I use Divine Yuri's mod this way as well (can't play without it, to be honest, I love it) and haven't had any issues with them playing nice together.

You may have figured all that out by now, but I thought I'd put it here for posterity if nothing else. Thanks for taking the time to submit an issue!
