### ISSUE TITLE
Incompatible with Chao Quick UI?

### ISSUE THREAD

**Issue by somohexuals** [kblease/ProductionQueue#23]
It wont let me place districts/wonders and after I've started making something (like a builder) I can't re-open the production list to change what is being produced until it's finished.

**Comment by somohexuals** [comment]
Just found that this has been addressed multiple times in the forum thread, sorry.

**Comment by kblease** [comment]
Unfortunately it is incompatible with CQUI. BUT, chaorace said [here](https://github.com/chaorace/cqui/issues/34#issuecomment-261164526) in his repo that he's started working on integrating Production Queue into it.

Your reply just came in. No worries! I don't mind answering any question. Thanks for the interest!

**Comment by chaorace** [comment]
@somohexuals No longer! As of 15fa14f79bbfaec1ebed85638f5701a35bc4dd44 the latest Production Queue mod is integrated
