### ISSUE TITLE
Unable to Place Districts

### ISSUE THREAD

**Issue by Pengr33n** [kblease/ProductionQueue#35]
I am unable to place any districts with your mod running.  When I click on a district, the choose production panel is hidden like normal so that I can select a tile.  The appropriate bonuses (science, faith, etc.) also show on each tile.  But when I left click nothing happens.  No matter what I do I can't assign the production of a district to a tile.  The only other mod I am using is Divine Yuri's Custom City Panel.

**Comment by kblease** [comment]
By default, Divine Yuri's Custom City Panel conflicts with Production Queue. If you comment out the lines for the ProductionPanel files from the modinfo file for Custom City Panel then everything should work fine. Those files are not actually used by Divine Yuri's mod. Hope this helps you!
