### ISSUE TITLE
Cannot place districts and wonders.

### ISSUE THREAD

**Issue by Sashkow** [kblease/ProductionQueue#39]
I can not any build districts or wonders anywhere in games where I enabled Production Queue mod. Green tiles appear but when I click to place a district nothing happens. I have no other mods.

Here is the thread on a forum that conforms it is not just me. https://steamcommunity.com/app/289070/discussions/3/1471966894877960550/?ctp=2

**Comment by kblease** [comment]
Hi @Sashkow, this is an old issue that was addressed after all the posts in the thread you linked. If you are running an up-to-date version of Civ VI and don't have any other mods installed, it should work. If your Civ VI game is not up-to-date it will almost definitely not work.

If you still are having an issue, please tell me which operating system you are using as well as the version number displayed in the bottom-left corner of the Civ VI main menu.

**Comment by Sashkow** [comment]
I ran the older ProductionQueue commit, thank you.

**Comment by kblease** [comment]
I'm glad you got it sorted out!

**Comment by heby1** [comment]
Fall update came today, same issue appeared. I have the newest version of mod, cannot place districts. OS: Windows 10, DirectX 12 version.
