### ISSUE TITLE
Purchase listing doesn't open for district buildings to be purchased

### ISSUE THREAD

**Issue by fleekix** [kblease/ProductionQueue#41]
When construct a district, the subsequent buildings are normally able to be purchased, but the panel doesn't expand, it only changes color from dark to light and back and forth.

**Comment by kblease** [comment]
Hmm, it works fine for me. What operating system are you running? Can you confirm which version of the game and mod you are using as well?

**Comment by fleekix** [comment]
Perhaps it was due to the game save file. I have started a new game and do not have the issue anymore. Could mark this closed as ambiguous.

**Comment by kblease** [comment]
Ahhh, interesting. Thanks for getting back to me.
