### ISSUE TITLE
Unable to repair wonders, after nuclear explosion

### ISSUE THREAD

**Issue by deXterbed** [kblease/ProductionQueue#45]
When i click on the wonder's name in the production menu, nothing happens..it won't even go in the queue!

**Comment by kblease** [comment]
This is one of those situations I had yet to organically encounter myself. This is very helpful to know, though. I hope to get to this some day.

**Comment by deXterbed** [comment]
thanks @kblease 😄

**Comment by kbjr** [comment]
Any news on this? Would _deeply_ like a fix for this
